nosana:
  description: Nosana Python Template

global:
  image: python:3.10-buster

  trigger:
    branch:
      - master

jobs:
  - name: install deps and build container
    commands:
      # Initialize
      - python -m venv count
      - . count/bin/activate
      - pip install -r requirements_prod.txt
      - ls
      - cd ..
      - ls
      - mlflow run project --env-manager=local --entry-point train --param-list team=Automatoes
      - ls 
      - ls mlruns
    artifacts:
      - name: count
        path: count/
